---
header_logo_url: /images/logo.jpg
header_logo_text: Lygaeoidea Species File
header_links:
  - label: Home
    link: /

  - label: Search DwC
    link: /resources/tw/filter/dwc_otus

  - label: Bibliography
    link: /resources/tw/filter/bibliography

  - label: Recent
    link: /recent

  - label: About
    link: /about
