---
  header_logo_url: http://lygaeoidea.speciesfile.org/HomePage/Lygaeoidea/img_Logo/SiteLogo.jpg
  header_logo_text: Lygaeoidea Species File
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
