issue_trackers:
  - label: Data
    description: E.g. missing data that I'd like to add, misspellings, broken link, or invalid data
    url: http://www.github.com/sfg-taxonpages/lygaeoidea/issues

  - label: Website
    description: E.g. suggest a new feature, report a broken panel, or other feature that is not working as expected
    url: http://www.github.com/SpeciesFileGroup/taxonpages/issues
